---
version: '2.4'
services:
  interestFetcher:
    cpus: 0.1
    mem_limit: 500m
    image: poanetwork/tokenbridge-oracle:latest
    env_file: ./.env
    environment:
      NODE_ENV: production
      INTEREST_FETCHER_PRIVATE_KEY: ${INTEREST_FETCHER_PRIVATE_KEY}
      INTEREST_FETCH_CONTRACT_ADDRESS: '0xCe13a234f4B13cccEf31e8596D6d9EB6eEd72D33'
      INTERVAL: 300000
    restart: unless-stopped
    entrypoint: yarn helper:interestFether
